#!/bin/bash
# Verificando se o yad está instalado no sistema
if [ -e /usr/bin/yad ] # Se o programa existe
then
	#interface gráfica
    	FORM=$(yad --form \
        	--title "SCP Transferência de Arquivos" \
        	--text "Digite as informações de transferência" \
        	--field="Arquivo Local" ""\
		--field="Usuário Remoto" ""\
        	--field="Host Remoto" ""\
        	--field="Caminho Remoto" ""\
        	--button="Cancelar:1" \
		--button="Transferir:0" 
	)

    	# Verificar se o usuário pressionou "Transferir"
    	if [ $? -eq 0 ]; then
        	# Obter valores dos campos
        	local_file=$(echo $FORM | cut -d'|' -f1)
        	remote_user=$(echo $FORM | cut -d'|' -f2)
        	remote_host=$(echo $FORM | cut -d'|' -f3)
        	remote_path=$(echo $FORM | cut -d'|' -f4)

        	# Realizar a transferência
        	scp "$local_file" "$remote_user@$remote_host:$remote_path"

        	yad --center --title "Concluído" --width=50 --height=80 --text "Transferência concluída!"
	else
        	yad --center --title "Cancelado" --width=50 --height=80 --text "Transferência cancelada."
    	fi

	# Chamar a função principal
	main

else
    $whiptail --infobox"Desculpe o Yad não foi encontrado !
          Em distro baseadas em Debian utilize para instalar:
          sudo apt-get install yad"
fi
